title: "Aulia Khalqillah"
author: "Aulia Khalqillah"
description: Media to share the knowledge

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "auliakhalqillah@usk.ac.id"
twitter_username: "aulia_khal"
github_username: "auliakhalqillah"
linkedin_username: "aulia-khalqillah-b6571315b"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Numerical-Method Seismic-Hazard Python GMT QGIS
